# General Configuration
title: "Azzeddine Habib's Portfolio"
description: "Explore my projects, skills, and experiences in technology."
author: 
  name: "Azzeddine Habib"
  email: "your-email@example.com"
  url: "https://siratchi-business.github.io/azzeddinehabib.github.io/"
baseurl: "" # Keep this empty if hosted on GitHub Pages
url: "https://siratchi-business.github.io/azzeddinehabib.github.io/"

# Theme Configuration
theme: "minima" # Change the theme here if needed

# Social Media Links
social_links:
  - name: "GitHub"
    url: "https://siratchi-business.github.io/azzeddinehabib.github.io/"
    icon: "fab fa-github"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/azzeddinehabib/"
    icon: "fab fa-linkedin"
  - name: "Twitter"
    url: "https://twitter.com/azzeddinehabib"
    icon: "fab fa-twitter"

# Navigation
header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Plugins (requires Gemfile setup)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown and Syntax Highlighting
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Portfolio Data
portfolio:
  - title: "Project 1"
    image: "assets/images/project1.png"
    url: "/projects/project1/"
    description: "A brief description of Project 1."
  - title: "Project 2"
    image: "assets/images/project2.png"
    url: "/projects/project2/"
    description: "A brief description of Project 2."
